version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      app_network:
        ipv4_address: 172.16.10.2

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongodb
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - SECRET_KEY=production-secret-key-example
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    networks:
      app_network:
        ipv4_address: 172.16.10.3

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8000
      - HOST=localhost
      - PORT=0.0.0.0
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
      - DATABASE_NAME=network_checks
    networks:
      app_network:
        ipv4_address: 172.16.10.4

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1